// templates/vue/src/App.vue
<template>
  <div class="app">
    <header class="header">
      <h1>🌱 Private Green Travel Rewards</h1>
      <p class="subtitle">Vue.js + FHEVM SDK Example</p>
    </header>

    <main class="main">
      <!-- Connection Status Card -->
      <div class="card">
        <h2>📡 Connection Status</h2>
        <div class="status-grid">
          <div class="status-item">
            <span class="label">Wallet:</span>
            <span :class="walletClass">{{ walletStatus }}</span>
          </div>
          <div class="status-item">
            <span class="label">FHEVM:</span>
            <span :class="fhevmClass">{{ fhevmStatus }}</span>
          </div>
          <div class="status-item">
            <span class="label">Network:</span>
            <span class="value">{{ network }}</span>
          </div>
          <div v-if="account" class="status-item full-width">
            <span class="label">Account:</span>
            <span class="address">{{ formatAddress(account) }}</span>
          </div>
        </div>
        <button
          v-if="!account"
          @click="connectWallet"
          class="btn btn-primary"
          :disabled="isConnecting"
        >
          {{ isConnecting ? 'Connecting...' : 'Connect Wallet' }}
        </button>
      </div>

      <!-- Submit Travel Data Card -->
      <div v-if="account && isFhevmReady" class="card">
        <h2>🚲 Submit Travel Data</h2>
        <p class="description">
          Enter your carbon savings (kg CO₂). Data is encrypted using FHE before submission.
        </p>

        <div class="input-group">
          <label for="carbonSaved">Carbon Saved (kg CO₂):</label>
          <input
            id="carbonSaved"
            v-model.number="carbonSaved"
            type="number"
            placeholder="Enter carbon saved..."
            min="0"
            step="0.1"
            :disabled="isSubmitting"
          />
        </div>

        <button
          @click="submitData"
          class="btn btn-primary"
          :disabled="isSubmitting || !carbonSaved || carbonSaved <= 0"
        >
          {{ isSubmitting ? 'Submitting...' : 'Submit Encrypted Data' }}
        </button>

        <div v-if="message" :class="messageClass" class="message">
          {{ message }}
        </div>

        <!-- Tier Information -->
        <div class="tier-info">
          <h3>Reward Tiers:</h3>
          <div class="tier-grid">
            <div class="tier">
              <span class="tier-name">Bronze</span>
              <span class="tier-value">&lt; 50 kg</span>
            </div>
            <div class="tier">
              <span class="tier-name">Silver</span>
              <span class="tier-value">50-99 kg</span>
            </div>
            <div class="tier">
              <span class="tier-name">Gold</span>
              <span class="tier-value">100+ kg</span>
            </div>
          </div>
        </div>
      </div>

      <!-- SDK Integration Example -->
      <div class="card">
        <h2>💻 Vue SDK Integration</h2>
        <div class="code-example">
          <pre><code>{{ sdkExample }}</code></pre>
        </div>
      </div>
    </main>

    <footer class="footer">
      <p>Built with FHEVM SDK • Zama Technology • Vue 3 + TypeScript</p>
    </footer>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useFhevm } from './composables/useFhevm'

const CONTRACT_ADDRESS = '0xA15ED92d12d602e0f2024C7AFe3692F17bCe6FA2'
const CONTRACT_ABI = [
  'function submitTravelData(bytes calldata encryptedCarbonSaved) external',
  'event TravelDataSubmitted(address indexed user, uint256 timestamp)'
]

// State
const carbonSaved = ref<number>(0)
const message = ref('')
const messageType = ref<'success' | 'error' | 'info'>('info')
const isConnecting = ref(false)
const isSubmitting = ref(false)

// Use FHEVM composable
const {
  account,
  network,
  isFhevmReady,
  connectWallet: connect,
  encrypt,
  getContract
} = useFhevm()

// Computed
const walletStatus = computed(() => account.value ? 'Connected' : 'Not Connected')
const fhevmStatus = computed(() => isFhevmReady.value ? 'Ready' : 'Initializing...')
const walletClass = computed(() => account.value ? 'status-connected' : 'status-disconnected')
const fhevmClass = computed(() => isFhevmReady.value ? 'status-connected' : 'status-pending')
const messageClass = computed(() => `message-${messageType.value}`)

const sdkExample = computed(() => `// Vue 3 Composition API
import { useFhevm } from './composables/useFhevm'

const {
  account,
  isFhevmReady,
  encrypt
} = useFhevm()

// Encrypt data
const encrypted = await encrypt(value, 'uint32')

// Submit to contract
const contract = getContract(address, abi)
await contract.submitTravelData(encrypted)`)

// Methods
const formatAddress = (address: string): string => {
  return `${address.substring(0, 6)}...${address.substring(38)}`
}

const connectWallet = async () => {
  isConnecting.value = true
  try {
    await connect()
    message.value = 'Wallet connected successfully!'
    messageType.value = 'success'
  } catch (error) {
    message.value = `Connection failed: ${error instanceof Error ? error.message : 'Unknown error'}`
    messageType.value = 'error'
  } finally {
    isConnecting.value = false
  }
}

const submitData = async () => {
  if (!carbonSaved.value || carbonSaved.value <= 0) {
    message.value = 'Please enter a valid carbon savings amount'
    messageType.value = 'error'
    return
  }

  isSubmitting.value = true
  message.value = 'Encrypting data with FHE...'
  messageType.value = 'info'

  try {
    // Step 1: Encrypt the data
    const encryptedValue = await encrypt(carbonSaved.value, 'uint32')
    message.value = 'Data encrypted! Submitting to blockchain...'

    // Step 2: Get contract instance
    const contract = getContract(CONTRACT_ADDRESS, CONTRACT_ABI)

    // Step 3: Submit transaction
    const tx = await contract.submitTravelData(encryptedValue)
    message.value = 'Transaction submitted! Waiting for confirmation...'

    // Step 4: Wait for confirmation
    await tx.wait()

    message.value = `✅ Success! Encrypted ${carbonSaved.value} kg CO₂ submitted to blockchain.`
    messageType.value = 'success'
    carbonSaved.value = 0
  } catch (error) {
    console.error('Submission error:', error)
    message.value = `❌ Error: ${error instanceof Error ? error.message : 'Unknown error'}`
    messageType.value = 'error'
  } finally {
    isSubmitting.value = false
  }
}

onMounted(() => {
  // Auto-connect if wallet was previously connected
  if (window.ethereum) {
    window.ethereum.request({ method: 'eth_accounts' })
      .then((accounts: string[]) => {
        if (accounts.length > 0) {
          connect()
        }
      })
      .catch(console.error)
  }
})
</script>

<style scoped>
.app {
  min-height: 100vh;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  padding: 2rem 1rem;
}

.header {
  text-align: center;
  color: white;
  margin-bottom: 2rem;
}

.header h1 {
  font-size: 2.5rem;
  margin: 0 0 0.5rem 0;
}

.subtitle {
  font-size: 1.1rem;
  opacity: 0.9;
  margin: 0;
}

.main {
  max-width: 800px;
  margin: 0 auto;
  display: flex;
  flex-direction: column;
  gap: 1.5rem;
}

.card {
  background: white;
  border-radius: 12px;
  padding: 2rem;
  box-shadow: 0 8px 16px rgba(0, 0, 0, 0.1);
}

.card h2 {
  margin: 0 0 1.5rem 0;
  color: #333;
  font-size: 1.5rem;
}

.status-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
  gap: 1rem;
  margin-bottom: 1.5rem;
}

.status-item {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 0.75rem;
  background: #f8f9fa;
  border-radius: 8px;
}

.status-item.full-width {
  grid-column: 1 / -1;
}

.label {
  font-weight: 600;
  color: #666;
}

.value {
  color: #333;
}

.address {
  font-family: monospace;
  color: #667eea;
  font-size: 0.9rem;
}

.status-connected {
  color: #10b981;
  font-weight: 600;
}

.status-disconnected {
  color: #ef4444;
  font-weight: 600;
}

.status-pending {
  color: #f59e0b;
  font-weight: 600;
}

.description {
  color: #666;
  margin-bottom: 1.5rem;
  line-height: 1.6;
}

.input-group {
  margin-bottom: 1.5rem;
}

.input-group label {
  display: block;
  font-weight: 600;
  color: #333;
  margin-bottom: 0.5rem;
}

.input-group input {
  width: 100%;
  padding: 0.75rem;
  border: 2px solid #e5e7eb;
  border-radius: 8px;
  font-size: 1rem;
  transition: border-color 0.2s;
}

.input-group input:focus {
  outline: none;
  border-color: #667eea;
}

.input-group input:disabled {
  background: #f3f4f6;
  cursor: not-allowed;
}

.btn {
  width: 100%;
  padding: 1rem;
  font-size: 1rem;
  font-weight: 600;
  border: none;
  border-radius: 8px;
  cursor: pointer;
  transition: all 0.2s;
}

.btn-primary {
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  color: white;
}

.btn-primary:hover:not(:disabled) {
  transform: translateY(-2px);
  box-shadow: 0 4px 12px rgba(102, 126, 234, 0.4);
}

.btn-primary:disabled {
  opacity: 0.6;
  cursor: not-allowed;
  transform: none;
}

.message {
  margin-top: 1rem;
  padding: 1rem;
  border-radius: 8px;
  font-weight: 500;
}

.message-success {
  background: #d1fae5;
  color: #065f46;
  border: 1px solid #10b981;
}

.message-error {
  background: #fee2e2;
  color: #991b1b;
  border: 1px solid #ef4444;
}

.message-info {
  background: #dbeafe;
  color: #1e40af;
  border: 1px solid #3b82f6;
}

.tier-info {
  margin-top: 2rem;
  padding-top: 2rem;
  border-top: 2px solid #e5e7eb;
}

.tier-info h3 {
  margin: 0 0 1rem 0;
  color: #333;
}

.tier-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
  gap: 1rem;
}

.tier {
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 1rem;
  background: linear-gradient(135deg, #667eea15 0%, #764ba215 100%);
  border-radius: 8px;
  border: 2px solid #667eea30;
}

.tier-name {
  font-weight: 700;
  color: #667eea;
  margin-bottom: 0.5rem;
  font-size: 1.1rem;
}

.tier-value {
  color: #666;
  font-size: 0.9rem;
}

.code-example {
  background: #1e293b;
  border-radius: 8px;
  padding: 1.5rem;
  overflow-x: auto;
}

.code-example pre {
  margin: 0;
}

.code-example code {
  color: #e2e8f0;
  font-family: 'Courier New', monospace;
  font-size: 0.9rem;
  line-height: 1.6;
}

.footer {
  text-align: center;
  color: white;
  margin-top: 2rem;
  padding: 1rem;
  opacity: 0.9;
}

@media (max-width: 640px) {
  .header h1 {
    font-size: 1.75rem;
  }

  .card {
    padding: 1.5rem;
  }

  .status-grid {
    grid-template-columns: 1fr;
  }
}
</style>

// examples/react/src/App.tsx
/**
 * React App Component
 * Demonstrates Universal FHEVM SDK usage with React + Vite
 */

import { useState } from 'react'
import { useFhevmInstance, useEncrypt } from '@fhevm/sdk/react'
import { ethers } from 'ethers'
import './App.css'

const CONTRACT_ADDRESS = '0x8Ac1d3E49A73F8328e43719dCF6fBfeF4405937B'
const CONTRACT_ABI = [
  'function submitTravelData(bytes calldata encryptedAmount) external',
  'function getCurrentPeriodInfo() external view returns (uint256, bool, bool, uint256, uint256, uint256, uint256)',
  'function getParticipantStatus(address participant) external view returns (bool, uint256, bool, uint256)'
]

function App() {
  const { fhevm, isReady } = useFhevmInstance()
  const { encrypt, isEncrypting } = useEncrypt()

  const [carbonSaved, setCarbonSaved] = useState<number>(5000)
  const [status, setStatus] = useState<string>('')
  const [account, setAccount] = useState<string>('')

  const connectWallet = async () => {
    if (typeof window.ethereum === 'undefined') {
      setStatus('❌ Please install MetaMask')
      return
    }

    try {
      const provider = new ethers.BrowserProvider(window.ethereum)
      const accounts = await provider.send('eth_requestAccounts', [])
      setAccount(accounts[0])
      setStatus(`✅ Connected: ${accounts[0].substring(0, 10)}...`)
    } catch (error) {
      setStatus(`❌ Connection failed: ${error instanceof Error ? error.message : 'Unknown'}`)
    }
  }

  const submitTravelData = async () => {
    if (!isReady || !fhevm) {
      setStatus('⏳ FHEVM not ready. Please wait...')
      return
    }

    if (!account) {
      setStatus('❌ Please connect wallet first')
      return
    }

    try {
      setStatus('🔐 Encrypting with @fhevm/sdk...')

      // ✅ SDK INTEGRATION: One-line encryption
      const encryptedValue = await encrypt(carbonSaved, 'uint32')

      setStatus('📡 Submitting to contract...')

      const provider = new ethers.BrowserProvider(window.ethereum)
      const signer = await provider.getSigner()
      const contract = new ethers.Contract(CONTRACT_ADDRESS, CONTRACT_ABI, signer)

      const tx = await contract.submitTravelData(encryptedValue)
      setStatus(`⏳ TX sent: ${tx.hash.substring(0, 15)}... Waiting...`)

      await tx.wait()
      setStatus(`✅ Success! Carbon savings submitted privately!`)
    } catch (error) {
      setStatus(`❌ Error: ${error instanceof Error ? error.message : 'Unknown'}`)
    }
  }

  return (
    <div className="app">
      <div className="card">
        <h1>🔐 React + Vite + FHEVM SDK</h1>
        <p className="subtitle">Privacy-preserving green travel rewards</p>

        {/* SDK Status */}
        <div className="status-box">
          <h3>SDK Status</h3>
          <div className="status-grid">
            <span>FHEVM:</span>
            <span>{isReady ? '✅ Ready' : '⏳ Loading...'}</span>
            <span>Network:</span>
            <span>Sepolia Testnet</span>
            {isReady && fhevm && (
              <>
                <span>Public Key:</span>
                <span className="monospace">{fhevm.publicKey.substring(0, 30)}...</span>
              </>
            )}
          </div>
        </div>

        {/* Wallet Connection */}
        <div className="section">
          <h3>1. Connect Wallet</h3>
          {!account ? (
            <button onClick={connectWallet} className="btn-primary">
              🦊 Connect MetaMask
            </button>
          ) : (
            <p className="success">✅ Connected: {account.substring(0, 15)}...</p>
          )}
        </div>

        {/* Submit Data */}
        <div className="section">
          <h3>2. Submit Encrypted Data</h3>
          <div className="input-group">
            <label>
              Carbon Saved (grams CO2e):
              <input
                type="number"
                value={carbonSaved}
                onChange={(e) => setCarbonSaved(Number(e.target.value))}
                min="1000"
                max="50000"
                disabled={!isReady || isEncrypting}
              />
            </label>
            <div className="tiers">
              <span className="tier bronze">🥉 Bronze (1k-5k): 10 tokens</span>
              <span className="tier silver">🥈 Silver (5k-10k): 25 tokens</span>
              <span className="tier gold">🥇 Gold (10k+): 50 tokens</span>
            </div>
          </div>
          <button
            onClick={submitTravelData}
            disabled={!isReady || !account || isEncrypting}
            className="btn-primary"
          >
            {isEncrypting ? '🔐 Encrypting...' : '🚀 Submit Encrypted Data'}
          </button>
        </div>

        {/* Status */}
        {status && (
          <div className="status-message">
            {status}
          </div>
        )}

        {/* Code Example */}
        <div className="code-section">
          <h3>💡 SDK Integration (3 lines!)</h3>
          <pre><code>{`import { FhevmProvider, useEncrypt } from '@fhevm/sdk/react'

// 1. Wrap app
<FhevmProvider config={{ network: 'sepolia' }}>
  <App />
</FhevmProvider>

// 2. Use hook
const { encrypt } = useEncrypt()

// 3. Encrypt & submit
const encrypted = await encrypt(value, 'uint32')
await contract.submitData(encrypted)`}</code></pre>
        </div>

        {/* Links */}
        <div className="links">
          <a href="https://docs.zama.ai" target="_blank" rel="noopener noreferrer">
            📚 Zama Docs
          </a>
          <a href={`https://sepolia.etherscan.io/address/${CONTRACT_ADDRESS}`} target="_blank" rel="noopener noreferrer">
            📝 Contract
          </a>
          <a href="https://github.com/..." target="_blank" rel="noopener noreferrer">
            💻 GitHub
          </a>
        </div>
      </div>
    </div>
  )
}

export default App
